### ISSUE TITLE
Přenesení z projektu

### ISSUE THREAD

**Issue by klobinoid** [peckadesign/PublicAccessModule#1]
@mhucik prosím o:

- [x] přenesení z modulu z Nay projektu
- [x] sepsání základního README, k čemu modul slouží a příklad, jak jej použít

Připrav do větve + PR, díky

**Comment by mhucik** [comment]
- hotovo ve větvi `1-preneseni-z-projektu`
- PR https://github.com/peckadesign/PublicAccessModule/pull/2

**Comment by mhucik** [comment]
Zamergováno, úkol zavírám
